package Login;

/**
 *
 * @author new jahs
 */
public class Menu extends javax.swing.JFrame {

    private Menu() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        jTSaldo.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
    }

    private static Menu instancia = null;

    public static Menu getInstancia() {
        if (instancia == null) {
            instancia = new Menu();
        }
        return instancia;
    }

    public void loadForm() {
        jTSaldo.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBRetiros = new javax.swing.JButton();
        jBConsignar = new javax.swing.JButton();
        jBOtras = new javax.swing.JButton();
        jLSaldo = new javax.swing.JLabel();
        jTSaldo = new javax.swing.JTextField();
        jBconsultas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                onFocus(evt);
            }
        });

        jBRetiros.setText("Retiros");
        jBRetiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetirosActionPerformed(evt);
            }
        });

        jBConsignar.setText("Consiganciones");

        jBOtras.setText("Otras Transacciones");

        jLSaldo.setText("Saldo Actual");

        jTSaldo.setEditable(false);
        jTSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSaldoActionPerformed(evt);
            }
        });

        jBconsultas.setText("Consulta de saldos y transacciones");
        jBconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jBRetiros))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jBConsignar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jBOtras))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLSaldo)
                        .addGap(18, 18, 18)
                        .addComponent(jTSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jBconsultas)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRetiros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConsignar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBOtras)
                .addGap(8, 8, 8)
                .addComponent(jBconsultas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSaldo)
                    .addComponent(jTSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSaldoActionPerformed

    private void jBconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultasActionPerformed
        Consultas.getInstancia().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jBconsultasActionPerformed

    private void jBRetirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetirosActionPerformed
        Retiros.getInstancia().loadForm();
        this.setVisible(false);
    }//GEN-LAST:event_jBRetirosActionPerformed
    public void setSaldo() {
        jTSaldo.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
    }
    private void onFocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_onFocus
        setSaldo();
    }//GEN-LAST:event_onFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsignar;
    private javax.swing.JButton jBOtras;
    private javax.swing.JButton jBRetiros;
    private javax.swing.JButton jBconsultas;
    private javax.swing.JLabel jLSaldo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTSaldo;
    // End of variables declaration//GEN-END:variables
}
