/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Retiros extends javax.swing.JFrame {
    
    private Retiros() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }
    
    private static Retiros instancia = null;    
    
    public static Retiros getInstancia() {
        if (instancia == null) {
            instancia = new Retiros();
        }        
        return instancia;
    }
    
    public void loadForm() {
        jlblSaldoDisponible.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
        jtxtMontoRetirar.setText("0");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRetirar = new javax.swing.JButton();
        jtxtMontoRetirar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlblSaldoDisponible = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formClose(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadForm(evt);
            }
        });

        jbtnRetirar.setText("Retirar");
        jbtnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRetirarActionPerformed(evt);
            }
        });

        jtxtMontoRetirar.setText("0");

        jLabel1.setText("Ingrese el monto a retirar");

        jlblSaldoDisponible.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtMontoRetirar)
                    .addComponent(jbtnRetirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSaldoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblSaldoDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jtxtMontoRetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnRetirar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRetirarActionPerformed
        if (retirar(Integer.parseInt(jtxtMontoRetirar.getText()))) {
            JOptionPane.showMessageDialog(null, "El retiro ha sido exitoso, recoja su dinero por favor");
            setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
            jlblSaldoDisponible.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
            Menu.getInstancia().setSaldo();
        } else {
            JOptionPane.showMessageDialog(null, "Recursos insuficientes, no puede retirar esta cantidad");
        }
    }//GEN-LAST:event_jbtnRetirarActionPerformed

    private void formClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formClose
        Menu.getInstancia().loadForm();
    }//GEN-LAST:event_formClose

    private void loadForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadForm
        jlblSaldoDisponible.setText(String.valueOf(Consultas.getInstancia().SaldoDisponible));
    }//GEN-LAST:event_loadForm

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Menu.getInstancia().loadForm();
    }//GEN-LAST:event_formWindowClosing
    
    private static boolean retirar(int monto) {
        boolean retiroExitoso = false;
        Consultas c = Consultas.getInstancia();
        if (monto <= c.SaldoDisponible) {
            c.SaldoDisponible -= monto;
            retiroExitoso = true;
        }
        return retiroExitoso;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnRetirar;
    private javax.swing.JLabel jlblSaldoDisponible;
    private javax.swing.JTextField jtxtMontoRetirar;
    // End of variables declaration//GEN-END:variables
}
